### ISSUE TITLE
Revised 'search' and catalog' icons.

### ISSUE THREAD

**Issue by L0ZZI** [grommet/grommet-icons#311]
Long overdue but here's a more proportional search icon and a revised catalog icon that fits our visual language better. Attached SVG's and Figma link, https://www.figma.com/file/oUqhjUvBzA8vS56Ld48gJc/Revised-Icons?node-id=1%3A384&t=hBLTfGCapnDPJb5q-1

I would try and fork the repository, but I'm not setup for it...
[Grommet-Revised_Icons.zip](https://github.com/grommet/grommet-icons/files/11191817/Grommet-Revised_Icons.zip)

----------------

**ToDos**
- [ ] Confirm the proposed icons are implemented with stroke as [requested here](https://github.com/grommet/grommet-icons/issues/311#issuecomment-1502260139).
- [ ] Add to icons library in Figma
- [ ] Add to `grommet-icons` repository

**Comment by ericsoderberghp** [comment]
I see both stroke and fill versions for the icons. We'd prefer stroke over fill as that makes scaling optional easier. OK?

**Comment by SmWorkGitHub** [comment]
Hi @L0ZZI. Can you tell me the intended usage of the "catalog" icon? This isn't to be used for the Contextual Help panel, is it?

**Comment by L0ZZI** [comment]
Yes.

**Comment by SeamusLeonardHPE** [comment]
This work has been subsumed by the icon work that @L0ZZI previewed at office hours on Aug 17th.

This ticket could be marked as done while we wait for the ticket to update all new icons, or should we use this as a dry run for the larger work to follow?

@SOjaHPE
